version: '3'
services:
  express:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_NAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_USER: postgres
      DATABASE_HOST: postgres
    volumes:
      - ./:/app
  
  
   

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
   
volumes:
  postgres-db:

